#!/bin/bash
# Derive a window-border accent colour from the current wallpaper, cache it,
# apply it to the running Hyprland, and persist it for the next session.
#
# Hyprland 0.55+ rejects `hyprctl keyword` while the config is Lua
# ("keyword can't work with non-legacy parsers. Use eval."), so the live update
# [disabled: fixed white border] # goes through `hyprctl eval`. The generated Lua file is loaded by
# lua/custom.lua, which is what carries the accent across a restart or reload.
set -euo pipefail

WALLPAPER_CACHE="$HOME/.cache/current_wallpaper"
# [disabled: fixed white border] ACCENT_LUA="$HOME/.cache/hypr-accent.lua"
COLOR_CACHE_DIR="$HOME/.cache/hypr-accent"

# Border alpha, as the last byte of Hyprland's rgba(RRGGBBAA) form. bf = 0.75,
# matching the static fallback in lua/window.lua.
ALPHA="bf"

# Fixed white border mode: accent disabled. Exit early and keep border white.
# To re-enable dynamic accent, delete the next two lines and uncomment the
# four "[disabled: fixed white border]" lines below.
if [[ "${HYPR_ACCENT_DISABLED:-1}" == "1" ]]; then exit 0; fi

wallpaper=$(cat "$WALLPAPER_CACHE" 2>/dev/null) || exit 0
[[ -f $wallpaper ]] || exit 0

mkdir -p "$COLOR_CACHE_DIR"

# Extraction costs ~240ms and ~150MB peak RSS for a 2560x1440 PNG, almost all of
# it the decode, so the result is cached per wallpaper. The key includes mtime,
# so editing or replacing an image recomputes just that one.
key=$(printf '%s:%s' "$wallpaper" "$(stat -c %Y "$wallpaper")" | md5sum | cut -d' ' -f1)
cache_file="$COLOR_CACHE_DIR/$key"

if [[ -s $cache_file ]]; then
  accent=$(<"$cache_file")
else
  # Quantise to 8 colours and score each one. The most *common* colour is
  # usually the near-black background, which makes a terrible border, so the
  # score favours saturation and mid lightness while still weighting by how much
  # of the image a colour covers -- otherwise a stray saturated speck wins.
  accent=$(magick "$wallpaper" -resize 200x200^ -colors 8 -format '%c' histogram:info:- | awk '
    function hexval(c,  i) { i = index("0123456789abcdef", tolower(c)); return i - 1 }
    function byte(s, at)   { return hexval(substr(s, at, 1)) * 16 + hexval(substr(s, at + 1, 1)) }
    {
      count = $1; sub(/:$/, "", count)
      hex = ""
      for (i = 1; i <= NF; i++) if ($i ~ /^#[0-9A-Fa-f]{6}/) { hex = tolower(substr($i, 2, 6)); break }
      if (hex == "" || count + 0 <= 0) next

      r = byte(hex, 1) / 255; g = byte(hex, 3) / 255; b = byte(hex, 5) / 255
      max = r; if (g > max) max = g; if (b > max) max = b
      min = r; if (g < min) min = g; if (b < min) min = b

      l = (max + min) / 2
      if (max == min)   s = 0
      else if (l > 0.5) s = (max - min) / (2 - max - min)
      else              s = (max - min) / (max + min)

      window = 1 - 2 * (l > 0.55 ? l - 0.55 : 0.55 - l)
      if (window < 0) window = 0

      score = s * window * log(count + 1)

      if (score > best)   { best = score;  best_hex = hex }
      if (l > lightest_l) { lightest_l = l; lightest_hex = hex }
    }
    END {
      # A fully greyscale wallpaper scores 0 everywhere; fall back to its
      # lightest tone so the border stays visible.
      if (best > 0)             print best_hex
      else if (lightest_hex != "") print lightest_hex
    }
  ')

  [[ -n $accent ]] || exit 0
  printf '%s' "$accent" >"$cache_file"
fi

# [disabled: fixed white border] lua="hl.config({ general = { col = { active_border = \"rgba(${accent}${ALPHA})\" } } })"

# [disabled: fixed white border] printf -- '-- Generated by scripts/wallpaper-accent.sh. Do not edit.\n%s\n' "$lua" >"$ACCENT_LUA"

# Not fatal if Hyprland is not up yet; custom.lua will pick the file up instead.
# [disabled: fixed white border] hyprctl eval "$lua" >/dev/null 2>&1 || true
