#!/usr/bin/env bash
# Renders the ACTIVE waybar files (config.jsonc / style.css) from the single sources
# configs/config.jsonc and styles/style.css, applying the current mode (.mode) as a
# small delta table plus the scale factor (.scale). The old per-mode source pairs
# (bar/dock x config/css) duplicated ~560 lines that differed by 9 config values and
# 2 CSS values.
#
# Waybar is GTK3 and has no scale setting, so "scaling" means multiplying every px value in
# the CSS, the bar height/margins in the config, and the inline Pango <span size='...'> values.
# Doing it at render time keeps the sources as a clean 1.0 baseline -- scaling is never
# applied on top of itself, so it stays lossless and repeatable.
#
# Mode deltas are BASELINE values, applied before scaling:
#   bar   hugs the top edge: margins 0, square top corners
#   dock  floats: margins 16/16/6, fully round
#
# Signals (RTMIN+n): 7 updates, 8 screenrec, 9 idle, 10 notif, 11 perf
#
# Usage: render.sh          (re-render using current .mode and .scale)
set -euo pipefail

DIR="$HOME/.config/waybar"
MODE=$(cat "$DIR/.mode" 2>/dev/null || echo bar)
SCALE=$(cat "$DIR/.scale" 2>/dev/null || echo 1.0)

case "$MODE" in bar|dock) ;; *) MODE=bar ;; esac
# Reject anything that isn't a plain positive number, then clamp to a sane range.
[[ "$SCALE" =~ ^[0-9]+(\.[0-9]+)?$ ]] || SCALE=1.0
awk -v s="$SCALE" 'BEGIN{exit !(s>=0.5 && s<=3.0)}' || SCALE=1.0

SRC_CONFIG="$DIR/configs/config.jsonc"
SRC_STYLE="$DIR/styles/style.css"
WARN="AUTO-GENERATED by render.sh -- edits here are DESTROYED on the next mode/scale change."

if [[ $MODE == bar ]]; then
    TOP_RADIUS="1px 1px 99px 99px"    # top corners square against the screen edge
    MR=0; ML=0; MT=0
else
    TOP_RADIUS="99px"
    MR=16; ML=16; MT=6
fi
export TOP_RADIUS MR ML MT

scale_css() {
    perl -pe 'BEGIN{$s=shift @ARGV} s/(\d+(?:\.\d+)?)px/sprintf("%gpx", $1*$s)/ge' "$1"
}

scale_jsonc() {
    # Only size-bearing keys are scaled. Never touch "interval", "signal", "timeout", etc.
    # These are all integer-valued in waybar (a fractional "height" is not accepted), and
    # Pango sizes are integer 1/1024ths, so round rather than truncate -- plain int() turned
    # 11500 * 1.15 into 13224 instead of 13225.
    perl -pe 'BEGIN{$s=shift @ARGV}
        s/("(?:height|border-radius|icon-size|spacing|margin-(?:top|bottom|left|right))"\s*:\s*)(\d+(?:\.\d+)?)/$1 . int($2*$s + 0.5)/ge;
        s/size='"'"'(\d+)'"'"'/sprintf("size=%c%d%c", 39, int($1*$s + 0.5), 39)/ge;
    ' "$1"
}

# Mode deltas. The regex anchors are unique strings in the sources; substitutions are
# no-ops in dock mode by construction (values already match).
apply_mode_config() {
    perl -pe '
        s/"margin-right": \d+/"margin-right": $ENV{MR}/;
        s/"margin-left": \d+/"margin-left": $ENV{ML}/;
        s/"margin-top": \d+/"margin-top": $ENV{MT}/;
    '
}

apply_mode_css() {
    perl -0777 -pe '
        s/(background-color: \@center;\n  border-radius: )99px;/${1}$ENV{TOP_RADIUS};/;
        s/(border-radius: )99px;(\n    \/\* Fill now comes)/${1}$ENV{TOP_RADIUS};$2/;
    '
}

# Atomic replace: stage each rendered file beside its target, then rename over it.
# A crash mid-render now leaves the previous good files intact instead of a
# truncated active config that launch.sh's restart loop would chew on forever.
# Both renames happen only after both renders succeed, so config/style stay a
# matched pair.
CONFIG_TMP="$DIR/config.jsonc.$$"
STYLE_TMP="$DIR/style.css.$$"
trap 'rm -f "$CONFIG_TMP" "$STYLE_TMP"' EXIT

{ printf '// %s Edit configs/config.jsonc instead.\n' "$WARN"; apply_mode_config < "$SRC_CONFIG" | scale_jsonc "$SCALE"; } > "$CONFIG_TMP"
{ printf '/* %s Edit styles/style.css instead. */\n' "$WARN"; apply_mode_css < "$SRC_STYLE" | scale_css "$SCALE"; } > "$STYLE_TMP"

mv -f "$CONFIG_TMP" "$DIR/config.jsonc"
mv -f "$STYLE_TMP" "$DIR/style.css"
trap - EXIT
