hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")

    hl.exec_cmd("~/.config/hypr/scripts/xdg.sh")
    hl.exec_cmd("~/.config/waybar/launch.sh")
    hl.exec_cmd("pgrep -f polkit-gnome-authentication-agent-1 >/dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("~/.config/hypr/scripts/gtk.sh")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Graphite-blue-Dark-compact'")
    hl.exec_cmd("pgrep -x hypridle >/dev/null || hypridle")
    hl.exec_cmd("wl-paste --watch cliphist store &")
    hl.exec_cmd("pgrep -x awww-daemon >/dev/null || awww-daemon")
    hl.exec_cmd("~/.config/hypr/scripts/restore_wallpaper.sh")
    hl.exec_cmd("pgrep -x nm-applet >/dev/null || nm-applet")
    hl.exec_cmd("pgrep -x blueman-applet >/dev/null || blueman-applet")
    hl.exec_cmd("xrdb ~/.Xresources")
    hl.exec_cmd("pkill -x dunst 2>/dev/null; pgrep -x mako >/dev/null || mako")
    hl.exec_cmd("pgrep -f 'gnome-keyring-daemon.*secrets' >/dev/null || gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("pgrep -f caffeine >/dev/null || caffeine")
    hl.exec_cmd("hyprctl setcursor Bibata-Original-Classic 25")
    hl.exec_cmd("hyprpm reload -n 2>/dev/null &")
    hl.exec_cmd("~/.config/waybar/scripts/perf.sh restore")
end)
